### PR TITLE
Adding scripts for DCS STATUS

### PR DESCRIPTION
**Pull request by mexanick**
Modulo frequency of the DCS DB updates this set of scripts works well. It takes about 5 minutes to run from lxplus. It looks 30 days back to query gas flow and 2 days back to query HV/LV/currents.
Known issue: due to uneven DCS DB updates sometimes data for certain fields (mostly LV) can be empty. In this case it means that this value didn't change during last two days and therefore the DB has not been updated, so such value can be taken from previous DOC daily report.

### CODE REVIEW

**Review by shaikhhasib — COMMENTED** [review]
The only thing I wan to mention that, we have to alert user   the DB time is -2 hours, so that user will not get confused.

**Comment by shaikhhasib** [comment]
We can also generate I-V plot only when detector is ON??, just to see the fluctuation in current when your detector is stable

**Comment by mexanick** [comment]
1. we have trending plots in DCS already
2. we are actually going to suffer the same as DCS: if the value wasn't updated last timeframe, you will have no value to plot.

**Comment by shaikhhasib** [comment]
Ok, Does DCS give you the plot when HV is "ON"??, I think you have to move your cursor over all value and try to find when was detector is 'ON', it will not give you separate plot in 'ON' condition.

Your second point is true.

**Comment by mexanick** [comment]
I'm merging the code to have the first version available for the others. Meanwhile we will try to improve the situation with the values which were not updated

**Pull request merged**
